return {
	Money = 0,

	BrainrotTools = {},
	BrainrotToolLevels = {},
	Pedestals = {},
	Movement = {
		SpeedLevel = 0,
		JumpLevel = 0,
	},
	PlotLevel = 0,

	Tutorial = {
		Step = 0,
		Completed = false,
	},

	DeveloperProducts = {
		SkipLevelCredits = 0,
	},

	GamePasses = {
		["1764317066"] = { owned = false, awarded = false },
		["1767395214"] = { owned = false, awarded = false },
	},

	BrainrotIndex = {
		Common = {
			["Matteo"] = { discovered = false },
			["Avocadini Guffo"] = { discovered = false },
			["Chimpanzini Bananini"] = { discovered = false },
			["Tung Tung Tung Sahur"] = { discovered = false },
			["Tim Cheese"] = { discovered = false },
			["Gangster Footera"] = { discovered = false },
			["Penguino Cocosino"] = { discovered = false },
			["Trippi Troppi"] = { discovered = false },
			["Bombardiro Crocodilo"] = { discovered = false },
		},
		Rare = {
			["Job Job Job Sahur"] = { discovered = false },
			["Zibra Zubra Zibralini"] = { discovered = false },
			["Bananita Dolphinita"] = { discovered = false },
			["Cacto Hipopotamo"] = { discovered = false },
			["Bandito Bobritto"] = { discovered = false },
			["Burbaloni Loliloli"] = { discovered = false },
			["Avocadorilla"] = { discovered = false },
			["Ballerina Cappuccina"] = { discovered = false },
			["Unclito Samito"] = { discovered = false },
		},
		Epic = {
			["Tipi Topi Taco"] = { discovered = false },
			["Talpa Di Fero"] = { discovered = false },
			["Avocadini Antilopini"] = { discovered = false },
			["Sigma Boy"] = { discovered = false },
			["Sigma Girl"] = { discovered = false },
			["Boneca Ambalabu"] = { discovered = false },
			["Caramello Filtrello"] = { discovered = false },
			["Glorbo Fruttodrillo"] = { discovered = false },
			["Alessio"] = { discovered = false },
		},
		Legendary = {
			["Pipi Avocado"] = { discovered = false },
			["Pandaccini Bananini"] = { discovered = false },
			["Perochello Lemonchello"] = { discovered = false },
			["Lionel Cactuseli"] = { discovered = false },
			["Carrotini Brainini"] = { discovered = false },
			["Cacasito Satalito"] = { discovered = false },
			["Lerulerulerule"] = { discovered = false },
			["Fragola La La La"] = { discovered = false },
			["Los Noobinis"] = { discovered = false },
		},
		Mythic = {
			["Brr es Teh Patipum"] = { discovered = false },
			["Graipuss Medussi"] = { discovered = false },
			["La Vacca Saturno Saturnita"] = { discovered = false },
			["Pot Hotspot"] = { discovered = false },
			["Spaghetti Tualetti"] = { discovered = false },
			["Strawberry Elephant"] = { discovered = false },
			["Tigroligre Frutonni"] = { discovered = false },
			["Torrtuginni Dragonfrutini"] = { discovered = false },
			["Blackhole Goat"] = { discovered = false },
		},
		Godly = {
			["Pakrahmatmamat"] = { discovered = false },
		},
	},
}
