local GameConfig = {}

-- GameConfig.GridSize = 48

-- GameConfig.SquareSize = Vector3.new(8, 1, 8)

-- GameConfig.Teams = {
-- 	{ name = "Blue", color = BrickColor.new("Bright blue") },
-- 	{ name = "Red", color = BrickColor.new("Bright red") },
-- }

-- GameConfig.PhaseConfig = {
-- 	INTERMISSION = {
-- 		id = "INTERMISSION",
-- 		duration = 30,
-- 		label = "Intermission",
-- 	},
-- 	TEAM_SELECTION = {
-- 		id = "TEAM_SELECTION",
-- 		duration = 10,
-- 		label = "Team Selection",
-- 	},
-- 	COUNTDOWN = {
-- 		id = "COUNTDOWN",
-- 		duration = 3,
-- 		label = "Get Ready!",
-- 	},
-- 	ROUND_START = {
-- 		id = "ROUND_START",
-- 		duration = 20,
-- 		label = "Round Start",
-- 	},
-- 	DETERMINE_WINNER = {
-- 		id = "DETERMINE_WINNER",
-- 		duration = 5,
-- 		label = "Determine Winner",
-- 	},
-- }

return GameConfig
