local BrainrotCatalog = {}

BrainrotCatalog.Names = {
	Common = {
		{ name = "Matteo", modelName = "Matteo", rarity = "Common", ratePerSecond = 1, chance = 42 },
		{ name = "Avocadini Guffo", modelName = "Avocadini Guffo", rarity = "Common", ratePerSecond = 2, chance = 20 },
		{
			name = "Chimpanzini Bananini",
			modelName = "Chimpanzini Bananini",
			rarity = "Common",
			ratePerSecond = 3,
			chance = 13,
		},
		{
			name = "Tung Tung Tung Sahur",
			modelName = "Tung Tung Tung Sahur",
			rarity = "Common",
			ratePerSecond = 4,
			chance = 9,
		},
		{ name = "Tim Cheese", modelName = "Tim Cheese", rarity = "Common", ratePerSecond = 5, chance = 6.5 },
		{ name = "Gangster Footero", modelName = "Gangster Footero", rarity = "Common", ratePerSecond = 6, chance = 5 },
		{
			name = "Penguino Cocosino",
			modelName = "Penguino Cocosino",
			rarity = "Common",
			ratePerSecond = 7,
			chance = 2.5,
		},
		{ name = "Trippi Troppi", modelName = "Trippi Troppi", rarity = "Common", ratePerSecond = 8, chance = 1.5 },
		{
			name = "Bombardiro Crocodilo",
			modelName = "Bombardiro Crocodilo",
			rarity = "Common",
			ratePerSecond = 9,
			chance = 0.5,
		},
	},
}

return BrainrotCatalog
